/* AUTO-GENERATED by scripts/sync-brand.py; do not edit. */
window.COULI_BRAND = Object.freeze({
  "schemaVersion": "couli.brand.v1",
  "identity": {
    "name": "凑狸",
    "projectId": "couli",
    "englishName": null,
    "tagline": null
  },
  "metadata": {
    "name": "凑狸",
    "version": "0.3.0",
    "date": "2026-10-04",
    "status": "project baseline",
    "theme": "light",
    "darkThemePhase": "P1",
    "colorSpace": "sRGB",
    "description": "当前项目使用的品牌与界面基线；2026-10-04 按设计方向第三轮调整 App 页面底、返利强调、平台来源标签与图片占位（docs/changes/20261004-设计方向第三轮.md）。已应用于根目录品牌配置、交付素材与品牌预览，不代表原生接入、Icon Composer 或真机验收完成。App 图标外观变体独立于 UI 主题。",
    "cssFontBase": 16,
    "sources": [
      "https://developer.apple.com/design/human-interface-guidelines/color",
      "https://developer.apple.com/design/human-interface-guidelines/accessibility"
    ]
  },
  "assets": {
    "logoMark": "../logo/source/logo-mark.svg",
    "logoHorizontal": "../logo/source/logo-horizontal.svg",
    "logoVertical": "../logo/source/logo-vertical.svg",
    "logoMono": "../logo/source/logo-mark-mono.svg",
    "logoInverse": "../logo/source/logo-mark-inverse.svg",
    "logoHorizontalInverse": "../logo/source/logo-horizontal-inverse.svg",
    "logoVerticalInverse": "../logo/source/logo-vertical-inverse.svg",
    "iconDefault": "../app-icon/icon-default.svg",
    "iconDark": "../app-icon/icon-dark.svg",
    "iconTinted": "../app-icon/icon-tinted.svg",
    "iconPng": "../app-icon/icon-1024.png",
    "iconForeground": "../app-icon/icon-foreground.png",
    "iconBackground": "../app-icon/icon-background.png",
    "iconMonochrome": "../app-icon/icon-monochrome.png"
  },
  "tokens": {
    "source": "../tokens/design-tokens.json",
    "css": "../tokens/variables.css"
  },
  "semantics": {
    "brandPrimary": {
      "token": "color.brand.primary",
      "cssVariable": "--color-brand-primary",
      "value": "#C44820"
    },
    "brandEmphasis": {
      "token": "color.brand.emphasis",
      "cssVariable": "--color-brand-emphasis",
      "value": "#A83B1F"
    },
    "canvas": {
      "token": "color.background.canvas",
      "cssVariable": "--color-background-canvas",
      "value": "#F2EEE6"
    },
    "adminCanvas": {
      "token": "color.background.admin-canvas",
      "cssVariable": "--color-background-admin-canvas",
      "value": "#F6F3ED"
    },
    "surface": {
      "token": "color.background.surface",
      "cssVariable": "--color-background-surface",
      "value": "#FFFFFF"
    },
    "imagePlaceholder": {
      "token": "color.background.placeholder",
      "cssVariable": "--color-background-placeholder",
      "value": "#E9E2D9"
    },
    "textPrimary": {
      "token": "color.text.primary",
      "cssVariable": "--color-text-primary",
      "value": "#28251F"
    },
    "textSecondary": {
      "token": "color.text.secondary",
      "cssVariable": "--color-text-secondary",
      "value": "#655E57"
    },
    "link": {
      "token": "color.text.link",
      "cssVariable": "--color-text-link",
      "value": "#A83B1F"
    },
    "price": {
      "token": "color.price.text",
      "cssVariable": "--color-price-text",
      "value": "#28251F"
    },
    "rebateText": {
      "token": "color.rebate.text",
      "cssVariable": "--color-rebate-text",
      "value": "#A83B1F"
    },
    "rebateBackground": {
      "token": "color.rebate.background",
      "cssVariable": "--color-rebate-background",
      "value": "#FBEFE8"
    },
    "rebateSolidBackground": {
      "token": "color.rebate.solid.background",
      "cssVariable": "--color-rebate-solid-background",
      "value": "#C44820"
    },
    "rebateSolidText": {
      "token": "color.rebate.solid.text",
      "cssVariable": "--color-rebate-solid-text",
      "value": "#FFFFFF"
    },
    "sourceText": {
      "token": "color.source.text",
      "cssVariable": "--color-source-text",
      "value": "#655E57"
    },
    "sourceBackground": {
      "token": "color.source.background",
      "cssVariable": "--color-source-background",
      "value": "#FFFFFF"
    },
    "sourceBorder": {
      "token": "color.source.border",
      "cssVariable": "--color-source-border",
      "value": "#E4DED5"
    },
    "pendingText": {
      "token": "color.status.pending.text",
      "cssVariable": "--color-status-pending-text",
      "value": "#655E57"
    },
    "pendingBackground": {
      "token": "color.status.pending.background",
      "cssVariable": "--color-status-pending-background",
      "value": "#EFEAE2"
    },
    "successText": {
      "token": "color.status.success.text",
      "cssVariable": "--color-status-success-text",
      "value": "#26735B"
    },
    "successBackground": {
      "token": "color.status.success.background",
      "cssVariable": "--color-status-success-background",
      "value": "#EAF4EE"
    },
    "warningText": {
      "token": "color.status.warning.text",
      "cssVariable": "--color-status-warning-text",
      "value": "#846020"
    },
    "warningBackground": {
      "token": "color.status.warning.background",
      "cssVariable": "--color-status-warning-background",
      "value": "#FBF2DC"
    },
    "errorText": {
      "token": "color.status.error.text",
      "cssVariable": "--color-status-error-text",
      "value": "#B42345"
    },
    "errorBackground": {
      "token": "color.status.error.background",
      "cssVariable": "--color-status-error-background",
      "value": "#FDECF0"
    },
    "primaryAction": {
      "token": "color.button.primary.default.background",
      "cssVariable": "--color-button-primary-default-background",
      "value": "#C44820"
    },
    "primaryActionText": {
      "token": "color.button.primary.default.text",
      "cssVariable": "--color-button-primary-default-text",
      "value": "#FFFFFF"
    },
    "controlBorder": {
      "token": "color.border.control",
      "cssVariable": "--color-border-control",
      "value": "#8A8177"
    },
    "focusRing": {
      "token": "color.focus.ring",
      "cssVariable": "--color-focus-ring",
      "value": "#26735B"
    }
  }
});
