'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const view = $('#app-view');
const state = {screen: 'home', navigation: ['home'], aiAvailable: true, orderTab: 'self', query: '', platform: 'all', product: 'cup', order: 'pending', message: '', aiMode: '', loadingTimer: null};
const priceNote = '券后价按单件计算，不含运费及会员价等优惠，以下单页为准';
const products = [
  {id:'cup',name:'轻量随行保温杯 · 350 mL',platform:'淘宝',price:'49',before:'59',coupon:'10',rebate:'3.2',after:'45.8',terms:['杯','保温','随行']},
  {id:'towel',name:'纯棉毛巾 · 2 条装',platform:'京东',price:'29.9',before:'34.9',coupon:'5',rebate:'1.5',after:'28.4',terms:['毛巾','纯棉']},
  {id:'bag',name:'轻便帆布收纳袋',platform:'拼多多',price:'19.9',before:'22.9',coupon:'3',rebate:'0.8',after:'19.1',terms:['包','袋','帆布','收纳']}
];
// Product illustration colors are decorative fixture art, independent of brand and status tokens.
const icons = {
  cup:'<ellipse cx="62" cy="107" rx="31" ry="5" fill="#CBD4BF"/><path d="M39 28h48l-5 70q-18 9-37 0Z" fill="#829870"/><path d="M39 28h23v75q-9 0-17-5Z" fill="#91A580"/><rect x="36" y="19" width="54" height="15" rx="6" fill="#3D5439"/><path d="M51 19v-5q0-4 4-4h18q4 0 4 4v5" fill="none" stroke="#3D5439" stroke-width="5"/><path d="M52 56h22M52 62h17" stroke="#E4E9DA" stroke-width="3"/>',
  towel:'<rect x="20" y="37" width="80" height="60" rx="8" fill="#B88753"/><rect x="24" y="29" width="72" height="57" rx="7" fill="#D4B086"/><path d="M32 68h56M32 76h56" stroke="#F5E5CF" stroke-width="4"/><path d="M29 32v48" stroke="#E5CAA7" stroke-width="3"/>',
  bag:'<path d="M27 43h66l6 61H21Z" fill="#71819C"/><path d="M43 43V30a17 17 0 0 1 34 0v13" fill="none" stroke="#4B5C78" stroke-width="7"/><path d="M31 43h9l-5 61H21Z" fill="#8997AE"/><rect x="48" y="65" width="27" height="17" rx="3" fill="#DDE2EA"/>'
};
function art(p, large = false){return `<span class="product-art ${p.id==='cup'?'':p.id}${large?' large-art':''}"><svg viewBox="0 0 120 120" role="img" aria-label="${p.name}原创示意插图">${icons[p.id]}</svg></span>`;}
function card(p, promotion = false){return `<article class="product"><div class="product-top">${art(p)}<div><span class="source">${p.platform}${promotion?' · 推广':''} · 示例商品</span><h4>${p.name}</h4><p class="price"><span>${p.platform==='拼多多'?'拼单':''}券后</span> <strong class="money">¥${p.price}</strong></p><p class="price-sub"><span>${p.platform==='拼多多'?'拼单':''}券前 <span class="money">¥${p.before}</span></span> · <span class="money-pair">券 ¥${p.coupon}</span></p></div></div><div class="product-bottom"><span class="badge rebate"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 预估返 ¥${p.rebate}</span><button type="button" class="secondary-action" data-product="${p.id}">查看商品</button></div></article>`;}
function title(text, logo = false){return `<h3 class="app-heading view-title" tabindex="-1">${logo?'<img src="../logo/source/logo-mark.svg" data-brand-asset="logoMark" alt="">':''}${text}</h3>`;}
function returnLabel(){const previous=state.navigation.at(-2);return {home:'返回首页',search:'返回搜索',ai:'返回 AI 助手',orders:'返回订单列表',order:'返回订单详情',me:'返回我的',wallet:'返回钱包',ledger:'返回收益明细',product:'返回商品详情',jump:'返回下单须知'}[previous]||'返回';}
function back(text, label = '返回'){return `<div class="back-row"><button type="button" data-back>← ${label}</button><h3 class="view-title" tabindex="-1">${text}</h3></div>`;}
function searchForm(id){return `<form class="search-form" data-form="search"><label class="sr-only" for="${id}">搜索示例商品</label><input id="${id}" name="search" type="search" placeholder="搜索商品" maxlength="80" autocomplete="off"><button class="icon-button" type="submit" aria-label="搜索"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg></button></form>`;}
function screenHome(){return `${title('凑狸',true)}<p class="app-kicker">好物，慢慢挑</p><p class="app-title">今天想找点什么？</p><div class="app-search">${searchForm('home-search')}${state.aiAvailable?'<button type="button" class="primary-action" data-screen="ai">问 AI</button>':''}</div><div class="paste-strip"><p>有商品链接或口令？</p><button type="button" class="secondary-action" data-action="paste">粘贴示例</button></div><h4 class="app-subtitle">日常好物</h4><div class="product-list">${products.map(p=>card(p,true)).join('')}</div><p class="disclaimer">${priceNote}</p>`;}
function screenSearch(){let matched=products.filter(p=>(!state.query||p.name.includes(state.query)||p.terms.some(t=>state.query.includes(t)))&&(state.platform==='all'||p.platform===state.platform));return `${state.navigation.length>1?back('搜索'):title('搜索')}${searchForm('search-input')}<p class="app-note">本地示例：试试「保温杯」「毛巾」或「收纳袋」。仅演示关键词匹配。</p><div class="chips" aria-label="筛选商品平台">${['all','淘宝','京东','拼多多'].map(x=>`<button type="button" data-platform="${x}" aria-pressed="${state.platform===x}">${x==='all'?'全部平台':x}</button>`).join('')}</div><p class="results-meta" id="search-summary" role="status"></p>${matched.length?`<div class="product-list">${matched.map(p=>card(p)).join('')}</div><p class="disclaimer">${priceNote}</p>`:'<div class="empty"><h4>没有匹配的示例商品</h4><p>可以更换关键词，或切换到全部平台。本页不代表真实平台的搜索结果。</p><button type="button" class="text-action" data-action="reset-search">查看全部示例</button></div>'}`;}
function screenAI(){return `${title('凑狸 AI 助手',true)}<div class="chat-intro"><p>说说你想找什么。商品来源、价格与预估返利会放在卡片里。</p><p class="chat-label">内容由 AI 生成，仅供参考</p></div><p class="app-note">下面四个问题是预置演示，不连接 AI 服务。</p><div class="chips"><button type="button" data-prompt="找一个 50 元以内的保温杯">50 元以内的保温杯</button><button type="button" data-prompt="查看示例订单进度">查看示例订单进度</button><button type="button" data-prompt="演示没有结果">演示没有结果</button><button type="button" data-prompt="演示加载失败">演示加载失败</button></div><div id="query" class="query" ${state.message?'':'hidden'}></div><div id="assistant-response" class="assistant-response" aria-live="polite" aria-atomic="true"></div><form class="query-form" data-form="ai"><label class="sr-only" for="message">输入演示问题</label><input id="message" name="message" placeholder="输入问题" maxlength="500" autocomplete="off"><button type="submit" class="primary-action">发送</button></form><p class="app-note">自填问题不会被发送。仅上述预置问题展示对应结果，其他内容会说明演示范围。</p>`;}
function renderAIResponse(){const response=$('#assistant-response');if(!response)return;$('#query').textContent=state.message;
  if(state.aiMode==='loading'){response.innerHTML='<div class="feedback pending"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 正在加载本地演示…</div>';return;}
  if(state.aiMode==='cup'){response.innerHTML=`<p>这是预算内的预置保温杯样例，数据来自本地演示，并非实际检索。</p>${card(products[0])}<p class="app-note">推荐商品含推广链接，购买后本平台可能获得佣金。此演示不会生成链接。</p><p class="disclaimer">${priceNote}</p>`;return;}
  if(state.aiMode==='order'){response.innerHTML='<p>这笔示例订单已收货，等待联盟结算，预计结算月份见卡片。</p><div class="order-card"><span class="source">淘宝 · 示例订单</span><h4>轻量随行保温杯</h4><span class="badge rebate"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 预估返 ¥3.2</span><p class="app-note">预计 11 月结算（虚构示例）</p><button type="button" class="secondary-action full" data-order="pending">查看示例订单详情</button></div>';return;}
  if(state.aiMode==='empty'){response.innerHTML='<div class="empty"><h4>没有结果 · 演示</h4><p>没找到相关商品，换个关键词试试。这是预设空状态，不是搜索结论。</p><button type="button" class="text-action" data-screen="search">使用普通搜索</button></div>';return;}
  if(state.aiMode==='error'){response.innerHTML='<div class="feedback error"><strong><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v7m0 3v2"/></svg> 加载失败 · 演示</strong><br>这是预设错误状态，输入内容已保留。</div><button type="button" class="secondary-action" data-action="retry-ai">重试保温杯示例</button>';return;}
  if(state.aiMode==='unknown'){response.innerHTML='<div class="feedback pending">此演示没有调用 AI，暂不能回答自填问题，也不会据此展示商品。请选择上方示例，或使用普通搜索。</div><button type="button" class="secondary-action" data-screen="search">使用普通搜索</button>';}
}
function screenProduct(){const p=products.find(x=>x.id===state.product);return `${back('商品详情')}${art(p,true)}<span class="source">${p.platform} · 虚构商品</span><h4 class="app-subtitle">${p.name}</h4><div class="detail-pricing"><p class="price"><span>${p.platform==='拼多多'?'拼单':''}券后</span> <strong class="money">¥${p.price}</strong></p><p class="price-sub"><span>${p.platform==='拼多多'?'拼单':''}券前 <span class="money">¥${p.before}</span></span> · <span class="money-pair">券 ¥${p.coupon}</span></p><span class="badge rebate"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 预估返 ¥${p.rebate}</span><div class="kv"><span>预估返后价</span><b>¥${p.after}</b></div><p class="app-note">预估返后价仅供参考，不是下单支付金额。返利以联盟结算金额为准。</p></div><p class="disclaimer">${priceNote}</p><p class="app-note">确认收货后随联盟月度结算入账。</p><button type="button" class="primary-action full" data-action="buy">领券购买 · 演示</button><p class="app-note">此处只演示外跳与返回，不会打开商家页面，也不会创建订单。</p>`;}
function screenJump(){const p=products.find(x=>x.id===state.product);return `${back('下单须知')}<p class="app-copy">真实购买时，请在打开的页面直接下单；不要加购后隔天购买，也不要再点击他人的推广链接。</p><p class="app-note">当前仅演示从凑狸前往${p.platform}的流程。登录与平台授权属于接入后流程，本演示不会请求账号信息。</p><button type="button" class="primary-action full" data-screen="external">继续查看外跳演示</button>`;}
function screenExternal(){const p=products.find(x=>x.id===state.product);return `${back('外跳演示')}<div class="mock-external"><h4>商家页面占位</h4><p>${p.platform} · ${p.name}</p><p class="app-note">没有打开真实商家，也没有下单。这里只展示用户主动外跳后，仍可返回凑狸。</p></div><button type="button" class="primary-action full" data-action="return-external">返回凑狸</button>`;}
function screenOrders(){return `<div class="order-head">${title('我的订单')}<button type="button" class="text-action" data-screen="find">找回订单</button></div><p class="app-note">演示账号 · 演示日期 2026-10-01</p><div class="seg order-tabs" aria-label="订单类型"><button type="button" data-order-tab="self" aria-pressed="${state.orderTab==='self'}">自购</button><button type="button" data-order-tab="shared" aria-pressed="${state.orderTab==='shared'}">分享</button></div>${state.orderTab==='self'?`<button type="button" class="order-item" data-order="pending"><span class="source">淘宝 · 今天 09:00</span><span class="badge pending"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 已收货，等待联盟结算</span><span class="order-product">${art(products[0])}<span><span class="order-product-title">轻量随行保温杯 · 350 mL</span><span class="order-product-meta">实付 <span class="money">¥49</span> · 1 件</span></span></span><span class="order-id">订单号 ****1001（示例）</span><span class="amount-row"><b>预估返 ¥3.2</b><span class="arrow">查看详情 →</span></span></button><button type="button" class="order-item" data-order="settled"><span class="source">京东 · 08-28</span><span class="badge settled"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg> 已结算</span><span class="order-product">${art(products[1])}<span><span class="order-product-title">纯棉毛巾 · 2 条装</span><span class="order-product-meta">实付 <span class="money">¥29.9</span> · 1 件</span></span></span><span class="order-id">订单号 ****0828（示例）</span><span class="amount-row"><b class="settled-amount">实返 ¥1.5</b><span class="arrow">查看详情 →</span></span></button>`:'<div class="empty"><h4>暂无分享订单</h4><p>这里是分享订单的空状态示例。分享商品产生的收益使用「推广收益」文案。</p></div>'}`;}
function screenOrder(){const done=state.order==='settled';return `${back('订单详情',returnLabel())}<span class="source">${done?'京东 · ****0828':'淘宝 · ****1001'} · 示例订单</span><div class="order-card"><span class="badge ${done?'settled':'pending'}">${done?'<svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg> 已结算':'<svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 已收货，等待联盟结算'}</span><h4>${done?'纯棉毛巾 · 2 条装':'轻量随行保温杯 · 350 mL'}</h4><p class="app-note">实付 ${done?'¥29.9':'¥49'} · 1 件</p><span class="badge ${done?'settled':'rebate'}">${done?'实返 ¥1.5':'预估返 ¥3.2'}</span>${done?'':'<p class="app-note">预计 11 月结算（虚构示例）</p>'}<ol class="timeline"><li class="recorded">付款<small>${done?'2026-08-28 10:20':'2026-10-01 09:00'}（示例）</small></li><li class="recorded">收货<small>${done?'2026-08-30 15:10':'2026-10-01 09:30'}（示例）</small></li><li class="${done?'recorded':'future'}">${done?'联盟结算':'预计 11 月结算'}<small>${done?'结算已完成（示例）':'等待联盟结算，月份仅为示例。'}</small></li><li class="${done?'complete':'future'}">已结算<small>${done?'2026-09-30 14:00（示例），实返已计入可提现余额。':'尚未发生，预估返利未计入可提现余额。'}</small></li></ol></div>${done?'<button type="button" class="primary-action full" data-screen="withdraw">去提现</button>':'<h4 class="app-subtitle">为什么还没结算？</h4><p class="app-copy">这笔样例订单已收货，仍在等待联盟月度结算。预估返利尚未计入可提现余额。</p>'}<button type="button" class="text-action full" data-info="order-help">返利说明</button>`;}
function screenFind(){return `${back('找回订单')}<p class="app-copy">找不到订单时，提交订单信息供核对。</p><p class="app-note">此页只检查示例格式，请勿输入真实订单或个人信息。</p><form data-form="find"><label class="field">购买平台<select name="platform"><option>淘宝</option><option>京东</option><option>拼多多</option></select></label><label class="field">示例订单号<input name="orderNumber" placeholder="DEMO-1001" maxlength="20" autocomplete="off" aria-describedby="find-hint"></label><p class="app-note" id="find-hint">仅支持 DEMO- 加 4 位数字。</p><button type="button" class="secondary-action full" data-action="fill-order">填入示例订单</button><button type="submit" class="primary-action full" style="margin-top:12px">预览找回申请</button></form><div id="find-feedback" role="status"></div><h4 class="app-subtitle">找回记录</h4><div class="empty"><p>暂无记录。本地演示不会提交或保存申请。</p></div>`;}
function screenMe(){return `${title('我的')}<p class="app-kicker">凑狸体验账号 · 虚构资料</p><div class="order-card"><p class="app-kicker">可提现余额</p><div class="balance">¥128.6</div><span class="badge settled"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg> 来自已结算收益</span><p class="app-note">演示累计余额，以下列表只展示部分订单。</p><button type="button" class="primary-action full" data-screen="wallet">查看钱包</button></div><div class="feedback pending"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 预估收益 ¥3.2<br>其中已收货 ¥3.2，预计 11 月结算。</div><button type="button" class="me-row" data-screen="ledger"><span>收益明细</span><span>→</span></button><button type="button" class="me-row" data-info="authorization"><span>平台授权</span><span>→</span></button><button type="button" class="me-row" data-info="help"><span>帮助中心</span><span>→</span></button><p class="app-note">我的页仅演示余额、预估收益与常用入口，其余账号功能未展开。</p>`;}
function screenWallet(){return `${back('钱包')}<div class="order-card"><p class="app-kicker">可提现余额</p><div class="balance">¥128.6</div><span class="badge settled"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg> 来自已结算收益</span><div class="wallet-stats"><p>冻结中<b>¥0</b></p><p>已提现<b>¥0</b></p></div><button type="button" class="primary-action full" data-screen="withdraw">提现 · 演示</button></div><div class="feedback pending"><strong><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></svg> 预估收益 ¥3.2</strong><br>其中已收货 ¥3.2，预计 11 月结算。</div><p class="app-note">按联盟最新预估计算，以联盟结算金额为准。预估收益不计入可提现余额。</p><button type="button" class="me-row" data-screen="ledger"><span>收益明细</span><span>→</span></button>`;}
function screenWithdraw(){const label=returnLabel();return `${back('提现预览',label)}<p class="app-copy">可提现余额 ¥128.6</p><div class="feedback pending">此演示不会提交提现，也不收集实名或收款信息。</div><p class="app-note">真实流程需要实名认证、本人收款账户、首次提现前签署劳务协议，以及二次验证；税费与实际到账金额由服务端返回。</p><button type="button" class="secondary-action full" data-back>${label}</button>`;}
function screenLedger(){return `${back('收益明细',returnLabel())}<p class="app-note">以下为最近一条余额流水样例，不代表完整账本。</p><div class="order-card"><span class="badge settled"><svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg> 已结算</span><h4>自购返利 <span class="money">+¥1.5</span></h4><p class="app-note">昨天 14:00 · 示例流水（演示日期 <span class="money">2026-10-01</span>）</p><button type="button" class="text-action" data-order="settled">查看关联<span class="money">订单 →</span></button></div>`;}
const screens={home:screenHome,search:screenSearch,ai:screenAI,product:screenProduct,jump:screenJump,external:screenExternal,orders:screenOrders,order:screenOrder,find:screenFind,me:screenMe,wallet:screenWallet,withdraw:screenWithdraw,ledger:screenLedger};
// Forward navigation appends a stable frame; Back only removes frames.
// A tab selection starts a new root. No mutable return-target chain is followed.
function navigationSection(){const root=state.navigation[0];return root==='search'?(state.aiAvailable?'home':'ai'):root;}
function goBack(){if(state.navigation.length<2)return;state.navigation.pop();state.screen=state.navigation.at(-1);render(true);}
function returnToProduct(){const index=state.navigation.lastIndexOf('product');if(index<0)return;state.navigation=state.navigation.slice(0,index+1);state.screen='product';render(true);}
function reconcileAINavigation(){
  if(!state.aiAvailable){
    const searchIndex=state.navigation.findIndex(screen=>screen==='ai'||screen==='search');
    if(searchIndex>=0){const descendants=state.navigation.slice(searchIndex+1).filter(screen=>screen!=='ai'&&screen!=='search');state.navigation=['search',...descendants];}
  }else if(state.navigation[0]==='search'){state.navigation=['home',...state.navigation];}
  state.screen=state.navigation.at(-1);
}
function render(focus = false){const previous=document.activeElement;const focusId=previous&&view.contains(previous)?previous.id:'';const focusData=previous&&view.contains(previous)?['orderTab','platform','prompt'].map(key=>[key,previous.dataset[key]]).find(([,value])=>value):null;view.innerHTML=screens[state.screen]();window.CouliBrand?.applyAssets(view);if(state.screen==='search'){ $('#search-input').value=state.query;$('#search-summary').textContent=state.query?`「${state.query}」的本地演示结果`:'全部示例商品';}if(state.screen==='ai')renderAIResponse();const section=navigationSection();$$('.tabbar [data-screen], .flow [data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen===section)));if(focus){const h=$('.view-title',view);h?.focus({preventScroll:true});view.scrollIntoView({block:'nearest',behavior:'instant'});}else if(focusId){document.getElementById(focusId)?.focus({preventScroll:true});}else if(focusData){$$('button',view).find(b=>b.dataset[focusData[0]]===focusData[1])?.focus({preventScroll:true});}}
function go(id, root = false){
  if(id==='ai'&&!state.aiAvailable)id='search';
  if(!screens[id])return;
  if(root||['home','ai','orders','me'].includes(id)){state.navigation=[id];}
  else if(state.navigation.at(-1)!==id){state.navigation.push(id);}
  state.screen=id;
  if(!state.aiAvailable&&id==='search')reconcileAINavigation();
  render(true);
}
function startAI(message, forcedMode){clearTimeout(state.loadingTimer);state.message=message;state.aiMode='loading';render();const modes={'找一个 50 元以内的保温杯':'cup','查看示例订单进度':'order','演示没有结果':'empty','演示加载失败':'error'};const next=forcedMode||modes[message]||'unknown';state.loadingTimer=setTimeout(()=>{state.aiMode=next;if(state.screen==='ai')renderAIResponse();},600);}
function info(key){const messages={
  'order-help':['返利说明','当前显示预置的订单状态。预估返利不等于可提现余额；只有完成结算后，才显示「已结算」和实返金额。真实状态与金额由订单接口提供。'],
  authorization:['平台授权 · 示例','真实购买前将按平台要求说明用途并请求授权。此演示不连接账号，也不会发起授权。'],
  help:['帮助中心 · 示例','可以在订单页查看进度，或进入「找回订单」预览找回申请。此演示不连接客服或提交工单。'],
  returned:['已返回凑狸','本次仅演示外跳与返回，没有下单或新增订单。你可以继续查看商品，或到订单页体验独立的预置订单样例。']
};const [heading,message]=messages[key];$('#info-title').textContent=heading;$('#info-message').textContent=message;$('#info-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.screen){go(b.dataset.screen,Boolean(b.closest('.tabbar,.flow')));return;}
  if(b.hasAttribute('data-back')){goBack();return;}
  if(b.dataset.product){state.product=b.dataset.product;go('product');return;}
  if(b.dataset.order){state.order=b.dataset.order;go('order');return;}
  if(b.dataset.orderTab){state.orderTab=b.dataset.orderTab;render();return;}
  if(b.dataset.platform){state.platform=b.dataset.platform;render();return;}
  if(b.dataset.prompt){startAI(b.dataset.prompt);return;}
  if(b.dataset.info){info(b.dataset.info);return;}
  if(b.dataset.action==='paste'){state.query='保温杯';state.platform='all';go('search');const note=document.createElement('p');note.className='feedback pending';note.textContent='已填入预置的保温杯示例，未读取剪贴板。';view.insertBefore(note,$('#search-summary'));return;}
  if(b.dataset.action==='reset-search'){state.query='';state.platform='all';render();return;}
  if(b.dataset.action==='buy'){go('jump');return;}
  if(b.dataset.action==='return-external'){returnToProduct();info('returned');return;}
  if(b.dataset.action==='retry-ai'){startAI('找一个 50 元以内的保温杯','cup');return;}
  if(b.dataset.action==='fill-order'){$('input[name="orderNumber"]',view).value='DEMO-1001';$('input[name="orderNumber"]',view).focus();}
});
document.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();
  if(f.dataset.form==='search'){state.query=f.elements.search.value.trim();state.platform='all';go('search');}
  if(f.dataset.form==='ai'){const value=f.elements.message.value.trim();if(value)startAI(value);else f.elements.message.focus();}
  if(f.dataset.form==='find'){const valid=/^DEMO-\d{4}$/.test(f.elements.orderNumber.value.trim());const output=$('#find-feedback');output.className=`feedback ${valid?'pending':'error'}`;output.innerHTML=valid?'示例格式检查通过。真实申请还需登录与平台核对；此演示未提交、未保存，也不会改动订单。':'<svg class="state-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v7m0 3v2"/></svg> 请填入 DEMO- 加 4 位数字，例如 DEMO-1001。请勿输入真实订单号。';f.elements.orderNumber.setAttribute('aria-invalid',String(!valid));}
});
$('#ai-available').addEventListener('change',e=>{state.aiAvailable=e.target.checked;$('#assistant-tab span').textContent=state.aiAvailable?'AI 助手':'搜索';$('#assistant-tab svg').innerHTML=state.aiAvailable?'<path d="M4 3h16v13H9l-5 5Z M8 8h8M8 12h5"/>':'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>'; $('.flow [data-screen="ai"] b').textContent=state.aiAvailable?'说需求':'搜商品';$('.flow [data-screen="ai"] small').textContent=state.aiAvailable?'短回答、商品卡与异常反馈':'关键词、平台筛选与商品结果';$('#availability-note').textContent=state.aiAvailable?'关闭后，首页保留搜索，第二个 Tab 改为「搜索」。':'AI 已设为不可用：普通搜索与商品卡仍可使用。';reconcileAINavigation();render();});
render();
